name: Test SBOM Images
# SBOM test, only builds base image
# 1st job builds the images, output a json array of all the image names
# 2nd job iterates list of images and generates sbom for each

on:
  push:
    branches: [ main, dev ]

jobs:
  build_images:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build containers
        run: |
          cp -R base/template_configs configs
          ./build_docker_compose.sh base api \
            --set "*.platform=linux/amd64,linux/arm64"
     - name: list images
       run: docker-compose images
     # generate the output TODO dynamic
     - name: List image output
       id: set-matrix
       run: echo "::set-output name=matrix::$(echo '[\"base\", \"api\"]')"
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

  sbom:
    needs: build_images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        #package: ${{ fromJson(["base", "api"]) }}
        package: ${{ fromJson(needs.build_images.outputs.matrix) }}
    steps:
      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          ## NOTE could use local image name // docker-compose images
          image: 'ghcr.io/spr-networks/super_${{ matrix.package }}'
