# NOTE move this to docker build yml
name: build and upload sbom artifact

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - uses: anchore/sbom-action@v0
      with:
        path: ./

    - uses: anchore/sbom-action/publish-sbom@v0
      with:
        sbom-artifact-match: ".*\\.spdx\\.json$"
